### ISSUE TITLE
Not finding library dir when building db

### ISSUE THREAD

**Issue by DrB-S** [fbreitwieser/krakenuniq#119]
**kraken_install_uniq/scripts/krakenuniq-build --db kUniq_std_minus_kdb --kmer-len 31 --threads 10 --taxids-for-genomes --taxids-for-sequences**
Kraken build set to minimize disk writes.
Finding all library files
find: ‘library/’: No such file or directory

**Comment by DrB-S** [comment]
Here are the contents of the kUniq_std_minus_kdb directory after running the command:                                                                  -rwxrwxr-x 1 becksts 8.1G Jul 21 08:01 database.idx
-rwxr-xr-x 1 becksts 377G Sep  7 12:34 database.kdb
-rwxrwxr-x 1 becksts 330K Jun 24 00:26 database.kdb.counts
-rwxrwxr-x 1 becksts 2.5M Sep  6 08:42 database100mers.kmer_distrib
-rwxrwxr-x 1 becksts 2.2M Sep  6 08:42 database150mers.kmer_distrib
-rwxrwxr-x 1 becksts 2.0M Sep  6 08:42 database200mers.kmer_distrib
-rwxrwxr-x 1 becksts 1.9M Sep  6 08:41 database250mers.kmer_distrib
-rwxrwxr-x 1 becksts 1.8M Sep  6 08:41 database300mers.kmer_distrib
-rwxrwxr-x 1 becksts 2.9M Sep  6 08:42 database50mers.kmer_distrib
-rwxrwxr-x 1 becksts 2.5M Sep  6 08:42 database75mers.kmer_distrib
-rw-rw-r-- 1 becksts    **0 Oct 19 16:59 library-files.txt**
-rwxrwxr-x 1 becksts 5.6M Jun 23 20:22 seqid2taxid.map
-rwxrwxr-x 1 becksts 116M Jun 23 20:23 taxDB

**Comment by shreyii** [comment]
hi @DrB-S what did you do to resolve this error?
