### ISSUE TITLE
Error while building the database 'std::bad_alloc'

### ISSUE THREAD

**Issue by MinLuke** [fbreitwieser/krakenuniq#129]
Hello everyone,
I have download microbial, archaea, parasitic worm and fungi genomes and then, to build the DB, I used the folllowing command

`./krakenuniq-build --db ../reference/ --kmer-len 31 --threads 3 --taxids-for-genomes --taxids-for-sequences --jellyfish-hash-size 40000000`

But I get this error message

```
Kraken build set to minimize disk writes.
Found 6 sequence files (*.{fna,fa,ffn,fasta,fsa}) in the library directory.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
db_sort: Getting database into memory ...Loaded database with 62272650591 keys with k of 31 [val_len 4, key_len 8].
Loaded database with 62272650591 keys with k of 31 [val_len 4, key_len 8].
db_sort: Sorting ...terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/home/minluke/aMeta/krakenuniq/build_db.sh: line 46: 10717 Annullato               db_sort -z -M -t 3 -n 15 -d database.jdb -o database0.kdb.tmp -i database.idx
```
And only database.idx and database.jbd are produced at the moment as files in my directory.
How can I resolve this issue?
thanks a lot

**Comment by QuietgraceH** [comment]
Hello, how did you solve the problem? I also encountered the same problem. Looking forward to your reply.
