### ISSUE TITLE
Why use adapters when building the database?

### ISSUE THREAD

**Issue by apredeus** [fbreitwieser/krakenuniq#147]
Dear KrakenUniq creators, 

Thank you very much for the excellent tool. It's been very useful in our project and is really a great tool all-around. 

I was wondering if there really is a necessity to include adapters into the database? I recently realised that they can essentially mask a more meaningful classification. That is, if 10 k-mers are assigned to some bacterial species, and 11 are assigned to a UniVec sequence, the overall classification would be to that of UniVec - which is just another way of saying "trim your adapters", which could be difficult if the adaptors are incorporated in somewhat irregular way. 

I was wondering if you have any comment on that? 

Thank you in advance!

**Comment by salzberg** [comment]
If you don't include vectors/adapters, then you can have reads that come from almost any species (human, yeast, bacteria) with adapters on them that will erroneously match some other species. Better to include them, even if you might occasionally fail to notice that a read from species X is more than just vector. Hope that makes sense.

**Comment by apredeus** [comment]
Hi Steven, 

Thank you for taking the time to answer! So I guess this automatically creates sort of a tradeoff between sensitivity and specificity: you either can detect more species without the adapters (some will be wrong), or can miss a few species, but have fewer false positives among the hits. 

This is perfect, thanks again!
