### ISSUE TITLE
build database error

### ISSUE THREAD

**Issue by wz115** [fbreitwieser/krakenuniq#162]
when I build database ,it give me the error info. I do not know it is error or just an warning(It means i can use this database as normal ):

Building  KrakenUniq LCA database (step 6 of 6)...
 Adding taxonomy IDs for sequences
 Adding taxonomy IDs for genomes
Reading taxonomy index from taxDB. Done.
Getting database0.kdb into memory (1.0 kB) ... Done
Loaded database with 0 keys with k of 31 [val_len 4, key_len 8].
Reading sequence ID to taxonomy ID mapping ... [starting new taxonomy IDs with 1000000001]ERROR with taxon [1000120010;assembly;GCF_034555355.1 Pseudomonas sp. B188] - parent taxon 3104264 not in database!
ERROR with taxon [1000120012;assembly;GCF_034555375.1 Pseudomonas sp. B33.4] - parent taxon 3104265 not in database!

**Comment by QuietgraceH** [comment]
Hello, how did you solve the problem? I also encountered the same problem. Looking forward to your reply.

**Comment by wz115** [comment]
> Hello, how did you solve the problem? I also encountered the same problem. Looking forward to your reply.
Yes.The taxonomy ID for these genome are wrong.I delete these genome sequences.
