### ISSUE TITLE
Kraken2Uniq

### ISSUE THREAD

**Issue by annabel-dekker** [fbreitwieser/krakenuniq#169]
Hi, 
I am just hoping to find some clarification. I have been reading the nature communications paper on best practices on how to use the kraken software suite. I was curious for testing Kraken2Uniq, but I can't find it anywhere. Is it embedded in this tool, or perhaps in the kraken2 tools? 
Many thanks in advance and have a great day!
Annabel

**Comment by salzberg** [comment]
Kraken2 has a 'unique' counting feature built in, although it counts unique minimizers rather than k-mers. That's much less intuitive, but it's available in Kraken2's report. (I think it is displayed by default but would have to check the manual to be sure.)

**Comment by annabel-dekker** [comment]
Thanks for the swift reply! I checked and indeed there is a built in function --report-minimizer-data. Thanks again.
