### ISSUE TITLE
4608 at ./tools/krakenuniq-download line 775.

### ISSUE THREAD

**Issue by nicolo-tellini** [fbreitwieser/krakenuniq#173]
Dear @fbreitwieser ,

The download of the `nt` database keep interrupting with the error attached below,

is it a problem on my side ? is there any alternative to download without using `curl` ?
[kraken-uniq.txt](https://github.com/fbreitwieser/krakenuniq/files/15399541/kraken-uniq.txt)

best,

nic

**Comment by salzberg** [comment]
Not sure what's happening but you should try getting the indices from the cloud resource that Ben Langmead established to make this easier:
  https://benlangmead.github.io/aws-indexes/k2
We have indices for both KrakenUniq and Kraken2 there.

**Comment by nicolo-tellini** [comment]
Hi @salzberg ;

thanks a lot. 
I have a quick question, can be the DB constructed with kraken2-build directly used as input in kraken-uniq ? 

best

nic

**Comment by salzberg** [comment]
No, the DB formats are not compatible between krakenuniq and kraken2.

**Comment by nicolo-tellini** [comment]
Thanks a lot, @salzberg I close the issue.

best

nic
