### ISSUE TITLE
krakenhll-download example doesn't work

### ISSUE THREAD

**Issue by gputzel** [fbreitwieser/krakenuniq#20]
I have tried this example command from the `README`:

`krakenhll-download --db DB --taxa "archaea,bacteria,viral,fungi,protozoa,helminths" --dust --exclude-environmental-taxa`

and nothing seems to happen. It just prints the usage information for the program.

This is on Mac OS X 10.13.5.

**Comment by fbreitwieser** [comment]
Hi @gputzel , you need to specify nt at the end, i.e. 
```
krakenhll-download --db DB --taxa "archaea,bacteria,viral,fungi,protozoa,helminths" --dust --exclude-environmental-taxa nt
```

**Comment by harshameghadri** [comment]
Hey florian,

Some error with the download command.

krakenhll-download --db DB --taxa "archaea,bacteria,viral,fungi,protozoa,helminths" --dust --exclude-environmental-taxa nt
Unknown database --taxa. 

krakenhll-download [<options>] <pattern> <pattern>*

**Comment by fbreitwieser** [comment]
Hi @harshameghadri , which version of KrakenHLL are you using?

**Comment by harshameghadri** [comment]
@fbreitwieser We have this version on our servers 

KrakenHLL/0.4.9

**Comment by Krischan** [comment]
Hi @harshameghadri, 
I had the same issue. I believe you need to enter a path for the <DB> parameter.

**Comment by harshameghadri** [comment]
This is what i did instead;

krakenhll-download -o centrifugeDB/ 'refseq/archaea' --dust --exclude-environmental-taxa nt

this I will repeat for viruses and bacteria and see how it goes.

maybe @gputzel  try this and let me know if it works as well.

**Comment by fbreitwieser** [comment]
hi @harshameghadri and @Krischan, I think this issue is resolved. If you continue having problems, please feel free to open a new issue.
