### ISSUE TITLE
Missing link option in install script

### ISSUE THREAD

**Issue by mbhall88** [fbreitwieser/krakenuniq#32]
https://github.com/fbreitwieser/krakenuniq/blob/80ac242f779c529845a167c1cbc123e761e5e430/install_krakenuniq.sh#L41

It seems the `-l` option is in the help menu for the install script but no option is actually created for it in `getopts`.

**Comment by fbreitwieser** [comment]
Hi @mbhall88, thanks for reporting the bug, I'll fix it soon.
