### ISSUE TITLE
Incorrect patern arguments for krakenuniq-download

### ISSUE THREAD

**Issue by mbhall88** [fbreitwieser/krakenuniq#35]
In the script `krakenuniq-download` it says one of the options for `<pattern>` is `microbial-nt` but looking in the perl script it appears this is not a recognised option and instead it should be `nt`
https://github.com/fbreitwieser/krakenuniq/blob/80ac242f779c529845a167c1cbc123e761e5e430/scripts/krakenuniq-download#L298

Can you please update either the usage docs to reflect this or the option in the `ARGV` parsing in the perl script.

**Comment by fbreitwieser** [comment]
Hi @mbhall88 , thanks for catching that. I'll fix the usage docs and script

**Comment by fbreitwieser** [comment]
Should be fixed - both `nt` and `microbial-nt` are now possible. Thanks again for catching that and using KrakenUniq!
