### ISSUE TITLE
Problem with database build after the last step, in "Setting values in the taxonomy tree"

### ISSUE THREAD

**Issue by VadimDu** [fbreitwieser/krakenuniq#38]
Dear developers/users,

I run the following command to build the database after downloading the required databases. I have used 350GB RAM to run the job:
krakenuniq-build -db KrakenUniq/DB/ --jellyfish-hash-size 10000M --threads 32 --taxids-for-genomes --taxids-for-sequences --max-db-size 300

It has completed successfully step 6:
"Building standard Kraken LCA database (step 6 of 6)...
 Adding taxonomy IDs for sequences
 Adding taxonomy IDs for genomes"

The last massage before the error was:
"Writing report file to database.report.tsv  ..
Reading genome sizes from ././database.kdb.counts ... done
Setting values in the taxonomy tree ..."

Then came:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
.../KrakenUniq/build_db.sh: line 277: 34721 Aborted krakenuniq --db . --report-file $REPNAME.report.tsv --threads $KRAKEN_THREAD_CT --fasta-input <( cat_library ) > $REPNAME.kraken.tsv

Can anyone please suggest as to what have happened here?
Thank you very much
Vadim

**Comment by jarrodscott** [comment]
Hi @VadimDu 

looks like you closed this issue, but did not explain why. Did you find a solution? My build is hung on this last step and Im afraid it will die soon. Any help or info from your experience would be great.

-Jarrod

**Comment by VadimDu** [comment]
Hi Jarrod,

I could not solve this error. However, the database was still built
successfully, with all the required files. I was able to run KrakenUniq
afterwards.

Hope that helps,
Vadim

**Comment by jarrodscott** [comment]
Hi Vadim

This is a huge help actually, thanks!. It means I just need patience...

**Comment by jarrodscott** [comment]
Hi Vadim
Just to clarify, the build you were running never actually completed the `database.report.tsv` or `database.kraken.tsv` files?

My process finally died. Looks like the last thing it was doing was ...

`Creating database summary report database.report.tsv ...` 

I assume what I have so far will suffice for classification? And this is what you meant when you said you were able to run KrakenUniq.

**Comment by VadimDu** [comment]
Hi Jarrod,

I can not recall at the moment, it was quite some time ago (and
unfortunately I have not used Kraken since then), but I think you are
correct about database.report and database.kraken files.

It should suffice for reads classification. This is what I meant in my
previous massage, I run KrakenUniq and was able to classify my reads.
After the database build step (which is very long), you should have several
output files (several hundred GB size, if you used nr - again sorry I do
not remember their names). The classification step itself is fast though!

Hope it helps,
Cheers,
Vadim
