### ISSUE TITLE
can't locate Fetch.pm

### ISSUE THREAD

**Issue by oeco28** [fbreitwieser/krakenuniq#55]

**Comment by Sithara85** [comment]
Hello, I am getting the below error when I try **krakenuniq-download --db dbdir taxonomy**, Why is this issue closed without any comment? I have only File/SortedSeek.pm


Can't locate File/Fetch.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./Kraken/krakenuniq-download line 10.

**Comment by Sithara85** [comment]
I figured out that I had to update some perl libraries to fetch files.
