### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by eclarke** [fbreitwieser/krakenuniq#8]
First, thanks for a neat improvement to Kraken- we're excited to try this on our data. 

I was wondering if you'd mind issuing releases on GitHub. It makes it a bit easier to package and distribute KrakenHLL on Bioconda because there's a set git tag to reference- right now we just go off commit hashes and it's a bit messy. Not a big deal, just a quality-of-life improvement.

Thanks again for this and your other useful metagenomic tools!

**Comment by eclarke** [comment]
Thanks, and glad to be of help, though it was @druvus who did all the heavy lifting for Bioconda :)

**Comment by fbreitwieser** [comment]
Dear @eclarke and @druvus , we changed the name of the method to KrakenUniq, which we hope is better to remember and has more focus on the feature of the method rather than the implementation. If you could update the Bioconda builds it would be greatly appreciated! Thanks,
Florian

**Comment by fbreitwieser** [comment]
Thanks!

**Comment by druvus** [comment]
krakenuniq 0.5.2 for linux is now available through Bioconda. The OSX build needs some more work as it needs to be built with gcc instead of default clang.
